### ISSUE TITLE
Similar request, different response??

### ISSUE THREAD

**Issue by GregDavid123** [eModbus/eModbus#107] opened 2021-10-13 14:59 UTC
#### Do not use to discuss topics! 
Hi @bertmelis, @Miq1, @postgetme and every one

My Aim is to use an ESP32 with the Max485 to get the state of a NORD motor through its Frequency inverter and control it.

**Describe the bug**

To test the set up, I connected it to the Modlink software through the USB and got the following responses:
The results vary between 
- The Valid response (occurs 65% of the time) 
- E4 - Server ID mismatch (occurs 30% of the time) 
- E5 -  Packet length error (occurs 5% of the time) 
 
When I connected the setup with similar request to the frequency inverter with similar parameters as the Modlink software, I got:
- E5 -  Packet length error (occurs 100% of the time) 

When I connected the  the frequency inverter with similar request and with similar parameters to the Modlink software, I get:
- The Valid response (occurs 100% of the time)

I also tried different ideas presented in #40 but non worked. 

According to Modlink all responses are suppose to be ok and good. So the problem comes from the reception of the response by the ESP32 (see last picture)

**Expected behavior**
I expected the connection between the ESP32 and the frequency inverter to give me 100% valid response.

**To Reproduce**
- Install Modlink (https://www.ozm.cz/ivobauer/modlink/downloads.htm)
- Try the code below 

**Example code**
```
#include <Arduino.h>
#include "ModbusClientRTU.h"
#include <math.h>

/*********************************************************
                   RT-485 DETAILS                     
*********************************************************/
#define BAUDRATE 38400   // 9600        // Baud rate for RT-485
#define ModbusMotor_ID 1 // ID of the frequency Inverter in the RTU Modbus System

//--- RS-485 communication wiring
#define ModbusRXD 22 //22isCorrect
#define ModbusTXD 25 //25isCorrect
#define ModbusFC 15  //RE & DE = FlowControl are connected with the GPIO 15

//--- RTU Modbus Constants
uint32_t Token = 1111;
uint8_t NumOfReq_Registers = 1;
const int NumOfResp_Registers = 1;
uint16_t AddressFirstHoldingRegister;
uint16_t ModbusRTU_result;

//--- Data collection constants
unsigned long collect_timeNow = 0;
unsigned long collect_timeOld = 0;
int collectTIME_interval = 60000 / 30;   //5000; // 60000 / 30; //30 readings per minute

// In my case the RS485 module had auto halfduplex, so no second parameter with the DE/RE pin is required!
ModbusClientRTU Modbus485(Serial2, ModbusFC);


void handleData(ModbusMessage response, uint32_t token)
{
  Serial.printf("Response: serverID=%d, FC=%d, Token=%08X, length=%d:\n", response.getServerID(), response.getFunctionCode(), token, response.size());
  for (auto &byte : response)
  {
    Serial.printf("%02X ", byte);
  }
  Serial.println("");
}

// Define an onError handler function to receive error responses
// Arguments are the error code returned and a user-supplied token to identify the causing request
void handleError(Error error, uint32_t token)
{
  // ModbusError wraps the error code and provides a readable error message for it
  ModbusError me(error);
  Serial.printf("Error response: %02X - %s\n", (int)me, (const char *)me);
}
//-------------------------------------------------------

//--- Motor Reading
void MotorReading()
{
  // //--- frequency Parameter (Hz) P716: read (1) 16-bit registers starting at Parameter P716 (register 0xB300) to RX buffer
  
AddressFirstHoldingRegister = 0xB300; //(4 und +1) - 3620

  Error err0 = Modbus485.addRequest(Token++, ModbusMotor_ID, READ_HOLD_REGISTER, AddressFirstHoldingRegister, NumOfReq_Registers );
  if (err0 != SUCCESS)
  {
    ModbusError e(err0);
    Serial.printf("Error creating request: %02X - %s\n", (int)e, (const char *)e);
  }
  else
  {
    // How do I get the response in a float variable e.g. ModbusRTU_result = xxx;  
  }
}

void setup()
{
  //--- Baud Rate
  Serial.begin(BAUDRATE);
  while (!Serial)
  {
  }
  Serial.println("Serial __ OK __");

Serial2.begin(BAUDRATE, SERIAL_8E1, ModbusRXD, ModbusTXD, true);

  //--- define the Slave ID
  pinMode(ModbusFC, OUTPUT);
  digitalWrite(ModbusFC, 0); // Init in receive mode
  //Set up ModbusRTU client.
  //- provide onData handler function
  Modbus485.onDataHandler(&handleData);
  // - provide onError handler function
  Modbus485.onErrorHandler(&handleError);
  // Set message timeout to 2000ms
  Modbus485.setTimeout(2000);
  // Start ModbusRTU background task
  Modbus485.begin();

  delay(10);
}

void loop()
{
  collect_timeNow = millis();
  int collectTimeCount = collect_timeNow - collect_timeOld;
  if (abs(collectTimeCount) >= collectTIME_interval) // Data is collected 
  {
    collect_timeOld = collect_timeNow;

  //--- Collect Sensor Data
  MotorReading();
   }
 }

```

**Additional context**
Response from Modlink to Esp32 conncection
![Modlink_3](https://user-images.githubusercontent.com/81199848/137158550-4a8e7408-bcfb-47c9-be4f-a68aa891fb01.PNG)
Response from Modlink to Esp32 conncection
![Modlink_2](https://user-images.githubusercontent.com/81199848/137158554-dcb6e497-f292-4e7d-9b79-777f5f55f10c.PNG)
Response from Modlink to Esp32 conncection
![Modlink_1](https://user-images.githubusercontent.com/81199848/137158556-93da718b-fafb-48ec-8a3e-b481e5b80204.PNG)

Response from Motor to Esp32 conncection
![Modbus_Motorresponse](https://user-images.githubusercontent.com/81199848/137158558-75135f76-0701-40f1-932d-0ccf8f149a5f.PNG)
.
According to Modlink all responses are suppose to be ok and good. So the problem comes from the reception of the response by the ESP32
![Modlink_4](https://user-images.githubusercontent.com/81199848/137162275-75f84532-70ca-42b3-85d8-61783a85ae44.PNG)
Thanks for your help.

**Comment by GregDavid123** [comment] 2021-10-14 07:23
@bertmelis I am using: MAX485CSA running on 5V.

@Miq1 I changed the pin numbering and updated the Libary as you suggested. Here are my results:
- When connected to Modlink
No right answer this time, but the following 
![Modlink_raw_2](https://user-images.githubusercontent.com/81199848/137270030-3df2810b-d660-4926-a1f8-fbc0c3e1706e.PNG)
![Modlink_raw_1](https://user-images.githubusercontent.com/81199848/137270037-fa0f98d9-6d31-4754-8e34-233b7c8bc70f.PNG)

Although everytime it is correct on Modlink
![Modlink_raw_3](https://user-images.githubusercontent.com/81199848/137270459-4d4035d9-db0d-406a-b395-36ed02270bd1.PNG)

- When connected to the Frequency converter, I only get 
![Modbus_Motor_raw_1](https://user-images.githubusercontent.com/81199848/137270256-67481b70-41e1-4bbf-9382-62cca752f0cd.PNG)

**Comment by Miq1** [comment] 2021-10-14 07:40
> So I guess you are right about the extra 0x00, please how can i get rid of them?

I am afraid the easiest way at the moment would be to get you some adapters with auto halfduplex...

In a parallel issue one of the users helped himself by filtering the leading and trailing 0x00 in the receive() function. This will cure the symptom, but not the root cause. 

You may experiment with the library's RE/DE toggle callback feature to use different timing patterns for the set and release of the toggle pin, but I cannot promise any progress. I have no regular adapters here to do testing myself unfortunately.

**Comment by Miq1** [comment] 2021-10-14 11:49
``_toggleLevel`` will be set to the value the library is attempting to set each time, so your changes to it will be lost at the time the next call is made.

I suppose you are trying to wait 500ms before releasing the toggle back to LOW level? Then you simply could do a ``delay(500);`` before the ``digitalWrite``.

**Comment by Miq1** [comment] 2021-10-14 12:30
You almost got it. You need to do the ``digitalWrite()`` yourself, though, so normally you would do a ``digitalWrite(_toggleLevel);`` any time around and do a ``if (_toggleLevel == LOW) delay(500);`` if that is what you are trying.

The delay on an ESP32 will halt the current task only, the others will continue running.

**Comment by Miq1** [comment] 2021-10-14 12:35
The sources I found in the Net describing the spurious 0x00 bytes effect were assuming that some voltages inside the RS485 adapter need to stabilize after the toggle before being able to correctly receive or send. I cannot judge if that is correct, but it would lend to a plausible explanation.

**Comment by GregDavid123** [comment] 2021-10-14 12:50
@Miq1  Ok thanks, so you mean the right expression will be: 

```
void togglefunction(bool _toggleLevel)
{
  if (_toggleLevel == LOW)
  {
    delay(500); // delay before it is turned off

  }
  else
  {
// delay before it is turned on is not required
  }

  digitalWrite(_toggleLevel);
}
```

> The sources I found in the Net describing the spurious 0x00 bytes effect were assuming that some voltages inside the RS485 adapter need to stabilize after the toggle before being able to correctly receive or send. I cannot judge if that is correct, but it would lend to a plausible explanation.

So what solution do u think of? 
By the way it sounds like it cannot be solved? so i will have to just solve the symptom. Which code could I then apply in the recieve() - in RTUutils and where should I apply it??

Thanks

**Comment by Miq1** [comment] 2021-10-14 12:59
There is an advice on AVRfreaks that sounds interesting: [link](https://www.avrfreaks.net/forum/rs485-framing-error-when-toggling-re-pin). Could you try to do a ``pinMode(rxpin, INPUT_PULLUP);`` in your ``setup()``? (Naming your RX pin of course).

For the "symptom curing" you need to throw away any leading 0 bytes after the buffer has been received and also any after the message proper. The latter is tricky as you will have to determine the regular length based on the function code and length bytes in the message, if applicable.

**Comment by bertmelis** [comment] 2021-10-14 14:02
> Rats. The `INPUT_PULLUP` advice sounded really promising... I found similar references at different places, so I was confident. cry

Unfortunately, this is managed by the Arduino core and the core set RX to `INPUT` only. If you are breadboarding you can try to add a (10k?) resistor to pullup off course.

**Comment by Miq1** [comment] 2021-10-14 14:45
> I don't have one now, I will try to get one and try it. Could can I use a resistor less or more than 10k?

4K7 will do as well, I reckon.

[Off topic] Something tells me your native language is rather German than English - do I guess that right? I am German myself 😁

**Comment by GregDavid123** [comment] 2021-10-14 14:53
@Miq1 OMG!!!! Awsome. The World is that small!
It is English but I have been in Germany for 6 years now and I often speak german so ja.

@bertmelis and @Miq1 I tried initialting the RXDpin after the Serial initialisation like this:


void setup()
{
  //--- Baud Rate
  Serial.begin(BAUDRATE);
  while (!Serial)
  {
  }
  Serial.println("Serial __ OK __");

Serial2.begin(BAUDRATE, SERIAL_8E1, ModbusRXD, ModbusTXD, true);

  //--- define the Slave ID
  pinMode(ModbusFC, OUTPUT);
  digitalWrite(ModbusFC, 0); // Init in receive mode
  //Set up ModbusRTU client.
  //- provide onData handler function
  Modbus485.onDataHandler(&handleData);
  // - provide onError handler function
  Modbus485.onErrorHandler(&handleError);
  // Set message timeout to 2000ms
  Modbus485.setTimeout(2000);
  // Start ModbusRTU background task
  Modbus485.begin();

  //--- Initialize the inputs and outputs
  pinMode(ModbusRXD, INPUT_PULLUP);

  delay(10);
}

and I get: 
![Modbus_Motor_raw_Init_change](https://user-images.githubusercontent.com/81199848/137342709-ff259b42-9f0d-4256-8426-cbae2986c2f7.PNG)

Although the pump and the frequency converter are active producing value greater than 0

**Comment by GregDavid123** [comment] 2021-10-18 10:28
@Miq1 
By the lines A and B also have a 56R on their respective lines, is that normal?

> Do you have or can get hold of a 2-channel oscilloscope? No high sampling frequencies required, a simple China brick will do. I would particularly be interested in the timing on the bus. 

Unfortunately i don't know where I can get an oscilloscope now. Can I use a multimeter?

> One last suspect I have is the Frequency inverter does closely follow the 3.5c and 1.5c gaps in the data stream - which the ESP32 is not.

Please what do you mean?

**Comment by Miq1** [comment] 2021-10-18 10:52
Oh well 😆 

No, a multimeter will show you a single, if changing value. The scope plots out both signals in parallel for a certain time to let you go back and forth in the recording, zoom in and out etc. Without it I am afraid you have few chances to catch a bug in timings.

3.5c and 1.5c are time gaps defined by the Modbus RTU specs to decide on end-of-message and invalid transmissions, respectively. The "c" stands for "character time".

In your case you have a baudrate of 38400 and 10 bits per character (8 data + 1 parity +1 stop bits). So one c would be 10/38400 - roughly 260 **microseconds**. 

According to the standard, if a client or server is noticing a quiet time of at least 3.5*260=910 microseconds, the bus is considered free and may start sending. The other value of 1.5c=390 microseconds in your case is the intra-message gap that may not occur in valid messages. If it is detected, the message shall be discarded.

These timings are hard to maintain on a multitasking device like the ESP32. Since most commercial RTU devices are relaxed in that respect as well, it works out nicely the most time.

There **are** devices, though, that will strictly adhere to the specs. With those the ESP32 may have a hard time communicating. In industrial Modbus applications sometimes baudrates of 1,000,000 and above are common with just a few microseconds for each character... 🙄

**Comment by Miq1** [comment] 2021-10-18 12:48
> I swtich them for the test. so only one device is connected. to the ESP32.

Let me drill that a bit more: how do you switch? Connect another set of A/B wires? Connect another RS485 adapter to the Serial pins?

**Comment by GregDavid123** [comment] 2021-10-18 13:10
@Miq1 
- Connection between ESP32 and Modlink (Computer):
The ESP32 has an adapter (MAX485). The A and B cables from this Max485 are then connected to another adapter (RS485 to USB) and then connected to the Computer.

- Connection between ESP32 and Frequency inverter:
The ESP32 has thesame an adapter (MAX485). Another cable is used which has and RJ12-connector on one side for ther FI and is open on the other end to connect to A and B (including GND and VCC) of the Max485. 

- Connection between Modlink (Computer)  and Frequency inverter:
The RJ12 cable mentioned above is used and connected to the A, B and GND of the RS485 to USB adapter, which is then connected to the Computer

**Comment by GregDavid123** [comment] 2021-10-18 17:44
@bertmelis  and @Miq1 Very intresting thoughts.

I will try them and let yout know.

The best way to see whether the mesaages are received will also be to write to a parameter.

Moreover i will get an RS485 repeater from amazon to try it tomorrow.

**Comment by GregDavid123** [comment] 2021-10-19 11:26
I am using IIOT AE04 (https://norvi.lk/industrial-esp32-norvi-iiot/) so such modification may be difficult, but I will see what I can do

**Comment by GregDavid123** [comment] 2021-10-19 12:54
I tried it again.

With the Modlink When 
Software Inverted no AB switch = Works
Software not Inverted no AB switched = No Response (time out)
Software Inverted and AB switched = Output is 00

**Comment by bertmelis** [comment] 2021-10-19 12:58
Looking at the wire diagram from Wikipedia (pasted above) and the truth table: the input at the UART would be:
`0 (start bit), 0 0 1 1 0 1 0 0`
which is the opposite of what RS485 is transmitting. Hence UART has to be inverted. However because MAX485 outputs HIGH when the inputs are open, you could say it doesn't need to be inverted otherwise the HIGH idle state could be treated as a start bit. Hence the 0x00.

**Comment by GregDavid123** [comment] 2021-10-19 13:11
By the way, when I don't invert them in the software (false), the voltage false instead of rising

NB: Measurement are being carried at the ESP32 side

**Comment by Miq1** [comment] 2021-10-19 13:11
> The fourth option is missing yet: software not inverted an AB switched

@GregDavid123 can you please try that and report the outcome?

**Comment by GregDavid123** [comment] 2021-10-19 13:37
@Miq1 Still 0x00 packet length error

**Comment by GregDavid123** [comment] 2021-10-19 16:54
OK, then I will try the first one 👍

**Comment by GregDavid123** [comment] 2021-10-19 16:54
OK, then I will try the first one 👍

**Comment by Miq1** [comment] 2021-10-21 08:50
> anyways, how do I read the results? What is A, B, C and 1/-1?

👍🏻

**Comment by GregDavid123** [comment] 2021-10-21 09:15
> No, as Bert stated, the internal is much too weak. You will have to add an external resistor of 470 Ohms. I suppose something near that value will do as well.

Ja, but I can't do much about that, given the ESP32 device i am using. That is why i just tried based on the info I had, and it worked.

> anyways, how do I read the results? What is A, B, C and 1/-1?
A, B, and C are the different factors I could change. while 1 and -1 which stand for a defined normal state and defined opposite state respectively. 

so the aim was to try out different possibilities (2³) to see their influence on the result.

**Comment by Miq1** [comment] 2021-11-11 09:58
Closing this now in regards to [discussions item #112](https://github.com/eModbus/eModbus/discussions/112).

**Closed by Miq1** 2021-11-11 09:58 UTC
Labels: bug
